<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Чат
    </h1>
</div>

<?php echo $this->getContent() ?>

<div class="form-group">
    <label for="fieldAuctionid" class="col-sm-2 control-label">Номер тендера</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['auctionId', 'type' => 'numeric', 'class' => 'form-control', 'id' => 'fieldAuctionid', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Название</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['name', 'size' => 50, 'class' => 'form-control', 'id' => 'fieldName', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategoryid" class="col-sm-2 control-label">Категория</label>
    <div class="col-sm-10">
        <?= $this->tag->select(['categoryId', $categories, 'using' => ['categoryId', 'categoryName'], 'class' => 'form-control', 'id' => 'fieldCategoryid', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Описание</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['description', 'size' => 1000, 'class' => 'form-control', 'id' => 'fieldDescription', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldaddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['address', 'size' => 100, 'class' => 'form-control', 'id' => 'fieldaddress', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDeadline" class="col-sm-2 control-label">Дата работ</label>
    <div class="col-sm-10">
        <?= $this->tag->dateField(['deadline', 'class' => 'form-control', 'id' => 'fieldDeadline', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Стоимость</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['price', 'type' => 'numeric', 'class' => 'form-control', 'id' => 'fieldPrice', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatestart" class="col-sm-2 control-label">Дата начала тендера</label>
    <div class="col-sm-10">
        <?= $this->tag->dateField(['dateStart', 'class' => 'form-control', 'id' => 'fieldDatestart', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateend" class="col-sm-2 control-label">Дата окончания тендера</label>
    <div class="col-sm-10">
        <?= $this->tag->dateField(['dateEnd', 'class' => 'form-control', 'id' => 'fieldDateend', 'readonly' => 'true']) ?>
    </div>
</div>


<?= $this->tag->hiddenField(['id']) ?>

<div id = "chat" class="layer">
    <table class="table-hover">
        <tbody>
        <?php foreach ($messages as $message): ?>
            <tr>
                <td class="with-background"><?php
                    if($message->getInput() != $owner)
                        echo 'Вы: ' . $message->getMessage() . ' (' .$message->getDate().')';
                    ?></td>
                <td class="with-background"><?php
                    if($message->getInput() == $owner)
                        echo  $otherUser->Userinfo->getFirstname() .' ' . $otherUser->Userinfo->getLastname() . ': '
                            .  $message->getMessage() . ' (' .$message->getDate().')';
                    ?></td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    var block = document.getElementById("chat");
    block.scrollTop = block.scrollHeight;
    //$("div.chat").scrollTop = $("div.chat").scrollHeight;
</script>

<?php
    echo $this->tag->form(
        [
            "coordination/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>



<div class="form-group">
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["message", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldMessage"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Отправить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
