<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Чат
    </h1>
</div>

<?php echo $this->getContent() ?>

<div id = "chat" class="layer">
    <table class="table-hover">
        <tbody>
        <?php foreach ($messages as $message): ?>
            <tr>
                <td class="with-background"><?php
                    if($message->getInput() != $owner)
                        echo 'Вы: ' . $message->getMessage() . ' (' .$message->getDate().')';
                    ?></td>
                <td class="with-background"><?php
                    if($message->getInput() == $owner)
                        echo  $otherUser->Userinfo->getFirstname() .' ' . $otherUser->Userinfo->getLastname() . ': '
                            .  $message->getMessage() . ' (' .$message->getDate().')';
                    ?></td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    var block = document.getElementById("chat");
    block.scrollTop = block.scrollHeight;
    //$("div.chat").scrollTop = $("div.chat").scrollHeight;
</script>

<?php
    echo $this->tag->form(
        [
            "coordination/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>



<div class="form-group">
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["message", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldMessage"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Отправить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
