

<div id="map">
    <div class="banner-form">
        <form action="#">
            <input type="text" class="form-control" placeholder="Поиск">
            <div class="dropdown tr-change-dropdown">
                <a data-toggle="dropdown" href="#" aria-expanded="false"><span class="change-text">Место</span><i class="fa fa-angle-down"></i></a>
                <ul class="dropdown-menu tr-change">

                </ul>
            </div><!-- /.category-change -->
            <button type="submit" class="btn btn-primary" value="Search">Найти</button>
        </form>
    </div><!-- /.banner-form -->
</div>


<div class="tr-users section-before bg-image">
    <div class="container text-center">
        <div class="row">
            <div class="col-sm-6">
                <div class="job-find">
                    <div class="icon">
                        <img src="/images/others/briefcase.png" alt="Icon" class="img-responsive">
                    </div>
                    <h1>Поиск заданий</h1>
                    <span>1 293 847 Заданий </span>
                    <a href="#" class="btn btn-primary">Найти задание</a>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="for-employers">
                    <div class="icon">
                        <img src="/images/others/man.png" alt="Icon" class="img-responsive">
                    </div>
                    <h1>Поиск исполнителей</h1>
                    <span>234 853 Исполнителей</span>
                    <a href="job-post.html" class="btn btn-primary">Создать задание</a>
                </div>
            </div>
        </div>
    </div><!-- /.container -->
</div><!-- /.tr-users -->


<!--TODO: сделать цикл по категориям -->

<div class="tr-category section-padding">
    <div class="container">
        <div class="section-title">
            <h1>Задания и исполнители по категориям</h1>
        </div>
        <ul class="category-list tr-list">
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category1.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Бухгалтерия</span>
                    <span class="category-quantity">(1298)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category2.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Обучение</span>
                    <span class="category-quantity">(612)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category3.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Строительство/ремонт</span>
                    <span class="category-quantity">(212)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/delivery.png" alt="Icon" class="img-responsive" style="max-height: 38px">
						</span>
                    <span class="category-title">Доставка</span>
                    <span class="category-quantity">(72)</span>
                </a>
            </li>
        </ul>
        <ul class="category-list tr-list">
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category5.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Менеджмент</span>
                    <span class="category-quantity">(1298)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category6.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Разработка/дизайн</span>
                    <span class="category-quantity">(7212)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category7.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Консалтинг</span>
                    <span class="category-quantity">(1298)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category8.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Медицина</span>
                    <span class="category-quantity">(212)</span>
                </a>
            </li>
        </ul>
        <ul class="category-list category-list-bottom tr-list">
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category9.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Творчество</span>
                    <span class="category-quantity">(212)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category10.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Маркетинг/продажи</span>
                    <span class="category-quantity">(972)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category11.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Производство</span>
                    <span class="category-quantity">(212)</span>
                </a>
            </li>
            <li>
                <a href="#">
						<span class="icon">
							<img src="/images/icons/category12.png" alt="Icon" class="img-responsive">
						</span>
                    <span class="category-title">Праздники</span>
                    <span class="category-quantity">(972)</span>
                </a>
            </li>
        </ul>
    </div><!-- /.container -->


</div><!-- /.tr-category -->
<div class="tr-steps bg-image section-padding section-before">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="step">
                    <div class="step-image">
                        <img src="/images/icons/step1.png" alt="/images" class="img-responsive">
                    </div>
                    <h1>1 Шаг</h1>
                    <h2>Зарегестрируйте аккаунт</h2>
                    <p>Зарегистрируйте аккаунт для того, чтобы иметь возможность создавать тендеры и участвовать в них.</p>
                </div><!-- step -->
            </div>
            <div class="col-sm-4">
                <div class="step">
                    <div class="step-image">
                        <img src="/images/icons/step2.png" alt="/images" class="img-responsive">
                    </div>
                    <h1>2 Шаг</h1>
                    <h2>Найдите или создайте тендер</h2>
                    <p>Для того, чтобы выбрать наилучшего исполнителя необходимо создать тендер на задание, в который будут вступать со своими предложениями исполнители</p>
                </div><!-- /.step -->
            </div>
            <div class="col-sm-4">
                <div class="step">
                    <div class="step-image">
                        <img src="/images/icons/step3.png" alt="/images" class="img-responsive">
                    </div>
                    <h1>3 Шаг</h1>
                    <h2>Выберите исполнителя</h2>
                    <p>Выберите понравившееся предложение и обсудите подробнее фронт работ с исполнителем в персональном чате</p>
                </div><!-- /.step -->
            </div>
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.tr-steps -->

<div class="tr-fun-fact section-padding">
    <div class="container">
        <div class="fun-fact-content">
            <div class="row text-center">
                <div class="col-sm-4">
                    <div class="fun-fact">
                        <img src="/images/icons/fun-fact-color1.png" alt="/images" class="img-responsive">
                        <h1 class="counter">3,412</h1>
                        <span>Создано тендеров</span>
                        <p>Тендер - возможность выбрать исполнителя</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="fun-fact">
                        <img src="/images/icons/fun-fact-color2.png" alt="/images" class="img-responsive">
                        <h1 class="counter">9,543</h1>
                        <span>Создано предложений</span>
                        <p>Предложение - возможность заявить о себе</p>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="fun-fact">
                        <img src="/images/icons/fun-fact-color3.png" alt="/images" class="img-responsive">
                        <h1 class="counter">2,978</h1>
                        <span>Выполнено заданий</span>
                        <p>Задание - шанс доверится профессионалам</p>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.fun-fact-content -->
    </div><!-- /.container -->
</div><!-- /.tr-fun-fact -->

<div class="tr-download-app bg-image section-padding section-before">
    <div class="container text-center">
        <h1>Загрузите в Play Маркет</h1>
        <div class="app-content">
            <div class="row">
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app1.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Google Play</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app2.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>App Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app3.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Windows Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.app-content -->
    </div><!-- /.contaioner -->
</div><!--/. tr-download-app -->







<?php
$today = date("Y-m-d");
$query = $this->modelsManager->createQuery('SELECT * FROM Auctions, Tasks WHERE Tasks.status=\'Поиск\' AND Tasks.taskId=Auctions.taskId AND Auctions.dateEnd>:today:');

$auctions= $query->execute(
    [
        'today' => "$today",
    ]
);
$keys=['name','description','address','price','coords','deadline','dateStart','dateEnd','link'];
for( $i=0; $i<$auctions->count(); $i++)
{

    $val[]=$auctions[$i]->tasks->getName();
    $val[]=$auctions[$i]->tasks->getDescription();
    $val[]=$auctions[$i]->tasks->getAddress();
    $val[]=$auctions[$i]->tasks->getPrice();
    $x=(double)$auctions[$i]->tasks->getLatitude();
    $y=(double)$auctions[$i]->tasks->getLongitude();
    $coords[]=$x;
    $coords[]=$y;
    $val[]=$coords;
    $val[]=$auctions[$i]->tasks->getDeadline();
    $val[]=$auctions[$i]->auctions->getDateStart();
    $val[]=$auctions[$i]->auctions->getDateEnd();
    $val[]='http://localhost/auctions/viewing/'.$auctions[$i]->auctions->getAuctionId();
    $tasks[]=array_combine($keys,$val);
    unset($coords);
    unset($val);
}
$json=json_encode($tasks);
echo "<script>
                var values=".$json.";
                setMarks(values)
              </script>";
?>


