

<div class="page-header">
    <?php $this->assets->outputJs(); ?>
    <h1>
        Редактирование профиля
    </h1>
</div>




<?= $this->getContent() ?>

<?= $this->tag->form(['userinfo/save', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>
<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['firstname', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldFirstname', 'onclick' => 'return SignUp.validate();']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPatronymic" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['patronymic', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldPatronymic']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['lastname', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldLastname']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBirthday" class="col-sm-2 control-label">Дата рождения</label>
    <div class="col-sm-10">
        <?= $this->tag->dateField(['birthday', 'class' => 'form-control', 'id' => 'fieldBirthday']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMale" class="col-sm-2 control-label">Пол</label>
    <div class="col-sm-10">
        <?= $this->tag->selectStatic(['male', ['1' => 'Мужской', '0' => 'Женский'], 'class' => 'form-control', 'id' => 'fieldMale']) ?>

    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['address', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAddress']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAbout" class="col-sm-2 control-label">О себе</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['about', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAbout']) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRaitingExecutor" class="col-sm-2 control-label">Рейтинг исполнителя</label>
    <div class="col-sm-10">
        <?= $userinfo->getRaitingExecutor();/*$this->tag->numericField(['raitingExecutor', 'min' => '0', 'max'=>'10', 'class' => 'form-control', 'id' => 'fieldRaitingExecutor']) */?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRaitingClient" class="col-sm-2 control-label">Рейтинг заказчика</label>
    <div class="col-sm-10">
        <?= $userinfo->getRaitingClient();// $this->tag->numericField(['raitingClient', 'min' => '0', 'max'=>'10', 'class' => 'form-control', 'id' => 'fieldRaitingClient']) ?>
    </div>
</div>
<!--<div class="form-group">
    <label for="fieldPathToPhoto" class="col-sm-2 control-label">Путь к изображению профиля</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['pathToPhoto', 'length'=>'260', 'class' => 'form-control', 'id' => 'fieldPathToPhoto']) ?>
    </div>
</div>-->
<!--<div class="form-group">
    <div class="col-md-6 col-md-offset-3">
        <img src=
            <?php
            echo '"'.$userinfo->getPathToPhoto().'"';
            ?>
        >
    </div>
</div>-->



<!--
<div class="form-group">
    <label for="fieldExecutor" class="col-sm-2 control-label">Исполнитель</label>
    <div class="col-sm-10">
          <input type="checkbox" name="executor" onclick="<script type='text/javascript'{if (this.checked == true){this.checked=false}; else {this.checked=true};}/>"
          />
        <!--   <script>
            $("checkbox").on("click", function () {
                if($(this).attr("checked")==true){
                    $(this).attr("checked","false");
                    $(this).attr("value","1");

                }else {
                    $(this).attr("checked", "true");
                    $(this).attr("value","1");
                }
            })
        </script>



    </div>
</div>
-->



<!--<?= $this->tag->hiddenField(['id']) ?>-->

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->tag->submitButton(['Сохранить', 'class' => 'btn btn-default']) ?>
    </div>
</div>


</form>
<div class="col-md-6 col-md-offset-3">
    <div class="image-preview">
        <img id="preview" src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="">
    </div>
    <form id="upload-image" enctype="multipart/form-data">
        <div class="form-group">
            <input type="file" name="image" id="image">
        </div>
        <input type="submit" class="btn btn-default" id="btnImg">
    </form>
    <div id="result">
    </div>
</div>
