


    <?php $this->assets->outputJs(); ?>




<?= $this->getContent() ?>

<div class="tr-breadcrumb bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="user-image">
                <img src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="Image" class="img-responsive">
            </div>
            <div class="user-title">
                <h1><?= $userinfo->getLastName().' '.$userinfo->getFirstname().' '.$userinfo->getPatronymic() ?></h1>
            </div>
            <ul class="job-meta tr-list list-inline">
                <?php
                    if(!empty($userinfo->getAddress()))
                     echo '<li><i class="fa fa-map-marker" aria-hidden="true"></i>'.$userinfo->getAddress().'</li>';
                        ?>
                <!--
                <li><i class="fa fa-phone" aria-hidden="true"></i>+0123 456 789</li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">jhondoe@gmail.com</a></li>
                <li><i class="fa fa-briefcase" aria-hidden="true"></i>UI & UX Designer</li>-->
            </ul>
        </div>
    </div><!-- /.container -->
</div><!-- /.tr-breadcrumb -->


    <div class="tr-profile section-padding">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-md-3">
                    <div class="tr-sidebar">
                        <ul class="nav nav-tabs profile-tabs section" role="tablist">
                          <!-- <li role="presentation" class="active"><a href="#account-info" aria-controls="account-info" role="tab" data-toggle="tab"><i class="fa fa-life-ring" aria-hidden="true"></i> Профиль</a></li>-->
                            <li role="presentation"><a href="#resume" aria-controls="resume" role="tab" data-toggle="tab"><span><i class="fa fa-user-o" aria-hidden="true"></i></span> Профиль</a></li>
                            <li role="presentation"><a href="#edit-resume" aria-controls="edit-resume" role="tab" data-toggle="tab"><span><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span> Настройки</a></li>
                            <li role="presentation"><a href="#bookmark" aria-controls="bookmark" role="tab" data-toggle="tab"><span><i class="fa fa-bookmark-o" aria-hidden="true"></i></span> Любимые категории</a></li>
                            <!--  <li role="presentation"><a href="#archived" aria-controls="archived" role="tab" data-toggle="tab"><span><i class="fa fa-clone" aria-hidden="true"></i></span> Archived Apply Job</a></li>
                              <li role="presentation"><a href="#close-account" aria-controls="close-account" role="tab" data-toggle="tab"><span><i class="fa fa-scissors" aria-hidden="true"></i></span> Close Account</a></li>-->
                          </ul>
                          <a href="#" class="btn btn-primary"><i class="fa fa-cloud-download" aria-hidden="true"></i> <span>Download Resume as doc</span></a>
                      </div><!-- /.tr-sidebar -->
                </div>
                <div class="col-sm-8 col-md-9">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active account-info" id="account-info">
                            <div class="tr-fun-fact">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="fun-fact">
                                            <div class="fun-fact-icon">
                                                <img src="/images/icons/fun-fact4.png" alt="images" class="img-responsive">
                                            </div>
                                            <div class="media-body">
                                                <h1 class="counter">39</h1>
                                                <span>Размещенных заданий</span>
                                            </div>
                                        </div><!-- /.fun-fact -->
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="fun-fact">
                                            <div class="fun-fact-icon">
                                                <img src="/images/icons/fun-fact5.png" alt="images" class="img-responsive">
                                            </div>
                                            <div class="media-body">
                                                <h1 class="counter">32</h1>
                                                <span>Выполненных заданий</span>
                                            </div>
                                        </div><!-- /.fun-fact -->
                                    </div>
                                    <div class="col-sm-4">
                                        <div class="fun-fact">
                                            <div class="fun-fact-icon">
                                                <img src="/images/icons/fun-fact6.png" alt="images" class="img-responsive">
                                            </div>
                                            <div class="media-body">
                                                <h1 class="counter">27</h1>
                                                <span>Отзывов</span>
                                            </div>
                                        </div><!-- /.fun-fact -->
                                    </div>
                                </div><!-- ./row -->
                            </div><!-- /.tr-fun-fact -->

                            <div class="section display-information">
                                <div class="title title-after">
                                    <div class="icon"><img src="/images/icons/2.png" alt="Icon" class="img-responsive"></div>
                                    <span>Публичная информация</span>
                                </div>

                                <div class="change-photo">
                                    <div class="user-image">
                                        <img id="preview" src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="Image" class="img-responsive">
                                    </div>
                                    <div class="upload-photo">
                                        <label class="btn btn-primary" for="upload-photo">
                                            <input type="file" id="upload-photo">
                                            Изменить фото
                                        </label>
                                        <span class="max-size">Max 5 MB</span>
                                    </div>
                                </div>
                                <ul class="tr-list account-details">
                                    <div class="jqte_editor" id="edit" contenteditable="false">
                                    <li>ФИО<span><?= $userinfo->getLastName().' '.$userinfo->getFirstname().' '.$userinfo->getPatronymic() ?></span></li>

                                    <li>Адрес<span><?= $userinfo->getAddress() ?></span></li>
                                    <li>Дата рождения<span>
                                            <?php
                                            $birthday=date('d:m:Y',strtotime($userinfo->getBirthday()));
                                           echo $birthday;
                                            ?>
                                        </span></li>
                                    <li>Пол<span><?=$userinfo->getMale()?></span></li>
                                    <!--TODO чтобы текст выводился полностью со всеми переносами строк-->
                                    <li>О себе<span><?= $userinfo->getAbout() ?></span></li>
                                    </div>
                                    <!--TODO чтобы рейтинг заполнялся из бд-->
                                    <li class="language-proficiency code-edit-small" style="margin-top: 15px;">
                                        <div class="media-body">
                                            <div class="rating-star">
                                                <span class="pull-left code-edit">Рейтинг исполнителя</span>
                                                <div class="rating">
                                                    <input type="radio" checked ="star1" name="rating" /><label class = "full" for="star1"></label>

                                                    <input type="radio" checked id="star2" name="rating"/><label class="half" for="star2"></label>

                                                    <input type="radio" checked id="star3" name="rating"/><label class ="full" for="star3"></label>

                                                    <input type="radio" checked id="star4" name="rating"/><label class="half" for="star4"></label>

                                                    <input type="radio" id="star5" name="rating"/><label class ="full" for="star5"></label>

                                                    <input type="radio" id="star6" name="rating"/><label class="half" for="star6"></label>

                                                    <input type="radio" id="star7" name="rating"/><label class ="full" for="star7"></label>

                                                    <input type="radio" id="star8" name="rating"/><label class="half" for="star8"></label>

                                                    <input type="radio" id="star9" name="rating"/><label class ="full" for="star9"></label>

                                                    <input type="radio" id="star10" name="rating"/><label class="half" for="star10"></label>
                                                </div>
                                            </div>
                                            <div class="rating-star">
                                                <span class="pull-left code-edit">Рейтинг заказчика</span>
                                                <div class="rating">
                                                    <input type="radio"  checked id="star11" name="rating1" /><label class = "full" for="star11"></label>

                                                    <input type="radio"  id="star12" name="rating1"/><label class="half" for="star12"></label>

                                                    <input type="radio"  id="star13" name="rating1"/><label class ="full" for="star13"></label>

                                                    <input type="radio"  id="star14" name="rating1"/><label class="half" for="star14"></label>

                                                    <input type="radio"  id="star15" name="rating1"/><label class ="full" for="star15"></label>

                                                    <input type="radio"  id="star16" name="rating1"/><label class="half" for="star16"></label>

                                                    <input type="radio"  id="star17" name="rating1"/><label class ="full" for="star17"></label>

                                                    <input type="radio"  id="star18" name="rating1"/><label class="half" for="star18"></label>

                                                    <input type="radio"   id="star19" name="rating1"/><label class ="full" for="star19"></label>

                                                    <input type="radio"  id="star20" name="rating1"/><label class="half" for="star20"></label>
                                                </div>
                                            </div>
                                        </div>
                                    </li><!-- /.language-proficiency -->
                                </ul>
                                <button type="button" class="btn btn-primary col-md-4" id="change">Изменить</button>
                                <button type="button" class="btn btn-primary col-md-4" id="save" style="margin-left: 15px; display: none;">Сохранить</button>
                            </div><!-- /.display-information -->
                        </div>
                    </div>

                    <div class="section display-information">
                        <div class="title ">
                            <span class="tr-title">Отзывы</span>
                        </div>
                        <div class="media-body work-history">
                            <div class="comment-widgets m-b-20">
                            <ul class="tr-list">
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/1.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>James Anderson</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row ">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/2.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text active w-100">
                                            <h5>Michael Jorden</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/3.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>Johnathan Doeting</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/4.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>James Anderson</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry</p>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                        </div>

                </div>
                </div>
            </div>
        </div>
    </div>


<script type="text/javascript">
    $( document ).ready(function () {
        $('#change').click(function () {
            if($('#change').text()=='Изменить')
            {
                $('#edit').prop('contenteditable','true');
                $('#change').text('Отмена');
                $('#save').show();
            }
            else
            {
                $('#edit').prop('contenteditable','false');
                $('#change').text('Изменить');
                $('#save').hide();
            }
        })
    })
</script>
<!--
<?= $this->tag->form(['userinfo/save', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>
<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['firstname', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldFirstname', 'onclick' => 'return SignUp.validate();']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPatronymic" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['patronymic', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldPatronymic']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['lastname', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldLastname']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBirthday" class="col-sm-2 control-label">Дата рождения</label>
    <div class="col-sm-10">
        <?= $this->tag->dateField(['birthday', 'class' => 'form-control', 'id' => 'fieldBirthday']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMale" class="col-sm-2 control-label">Пол</label>
    <div class="col-sm-10">
        <?= $this->tag->selectStatic(['male', ['1' => 'Мужской', '0' => 'Женский'], 'class' => 'form-control', 'id' => 'fieldMale']) ?>

    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['address', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAddress']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAbout" class="col-sm-2 control-label">О себе</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['about', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAbout']) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRaitingExecutor" class="col-sm-2 control-label">Рейтинг исполнителя</label>
    <div class="col-sm-10">
        <?= $userinfo->getRaitingExecutor();/*$this->tag->numericField(['raitingExecutor', 'min' => '0', 'max'=>'10', 'class' => 'form-control', 'id' => 'fieldRaitingExecutor']) */?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRaitingClient" class="col-sm-2 control-label">Рейтинг заказчика</label>
    <div class="col-sm-10">
        <?= $userinfo->getRaitingClient();// $this->tag->numericField(['raitingClient', 'min' => '0', 'max'=>'10', 'class' => 'form-control', 'id' => 'fieldRaitingClient']) ?>
    </div>
</div> -->
<!--<div class="form-group">
    <label for="fieldPathToPhoto" class="col-sm-2 control-label">Путь к изображению профиля</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['pathToPhoto', 'length'=>'260', 'class' => 'form-control', 'id' => 'fieldPathToPhoto']) ?>
    </div>
</div>-->
<!--<div class="form-group">
    <div class="col-md-6 col-md-offset-3">
        <img src=
            <?php
            echo '"'.$userinfo->getPathToPhoto().'"';
            ?>
        >
    </div>
</div>-->



<!--
<div class="form-group">
    <label for="fieldExecutor" class="col-sm-2 control-label">Исполнитель</label>
    <div class="col-sm-10">
          <input type="checkbox" name="executor" onclick="<script type='text/javascript'{if (this.checked == true){this.checked=false}; else {this.checked=true};}/>"
          />
        <!--   <script>
            $("checkbox").on("click", function () {
                if($(this).attr("checked")==true){
                    $(this).attr("checked","false");
                    $(this).attr("value","1");

                }else {
                    $(this).attr("checked", "true");
                    $(this).attr("value","1");
                }
            })
        </script>



    </div>
</div>
-->



<!--<?= $this->tag->hiddenField(['id']) ?>-->
<!--
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->tag->submitButton(['Сохранить', 'class' => 'btn btn-default']) ?>
    </div>
</div>


</form>
<div class="col-md-6 col-md-offset-3">
    <div class="image-preview">
        <img id="preview" src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="">
    </div>
    <form id="upload-image" enctype="multipart/form-data">
        <div class="form-group">
            <input type="file" name="image" id="image">
        </div>
        <input type="submit" class="btn btn-default" id="btnImg">
    </form>
    <div id="result">
    </div>
</div>
-->