<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>Подработка</title>

       <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->
        <!--  <link rel="stylesheet" href="/css/styles.css"> -->
        <link rel="stylesheet" href="/css/bootstrap.min.css">
       <!-- <link rel="stylesheet" href="/css/bootstrap-theme.min.css"> -->
        <link rel="stylesheet" href="/css/font-awesome.min.css">
       <!-- <link rel="stylesheet" href="/css/style.css" >-->
        <link rel="stylesheet" href="/css/jquery-te.css">
        <link rel="stylesheet" href="/css/slick.css">
        <link rel="stylesheet" href="/css/main.css">
        <link rel="stylesheet" href="/css/responsive.css">




        <script type="text/javascript" src="/js/jquery.min.js"></script>
        <script type="text/javascript" src="/js/jquery-te.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/countdown.js"></script>
        <script type="text/javascript" src="/js/counterup.min.js"></script>
        <!--  <script type="text/javascript" src="/js/gmaps.min.js"></script> -->
        <script type="text/javascript" src="/js/inview.min.js"></script>
        <script type="text/javascript" src="/js/main.js"></script>
        <script type="text/javascript" src="/js/slick.min.js"></script>
        <!--  <script type="text/javascript" src="/js/utils.js"></script> -->
        <script type="text/javascript" src="/js/waypoints.min.js"></script>
        <!-- <script type="text/javascript" src="http://api-maps.yandex.ru/2.1/?lang=ru_RU"></script>
         <script type="text/javascript" src="/js/mapTender.js"></script>-->


       <!--  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">-->

        <link rel="icon" href="/images/ico/favicon.ico">
        <link rel="apple-touch-icon" sizes="144x144" href="/images/ico/apple-touch-icon-144-precomposed.png">
        <link rel="apple-touch-icon" sizes="114x114" href="/images/ico/apple-touch-icon-114-precomposed.png">
        <link rel="apple-touch-icon" sizes="72x72" href="/images/ico/apple-touch-icon-72-precomposed.png">
        <link rel="apple-touch-icon" sizes="57x57" href="/images/ico/apple-touch-icon-57-precomposed.png">


    </head>
    <body>
    <?php echo $this->getContent(); ?>

        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
       <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>-->
        <!-- Latest compiled and minified JavaScript -->
        <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>-->


       <!-- <script src="/js/utils.js"></script>-->
    </body>
</html>
